import type { Node, Edge } from '@xyflow/react'
import type { ArchNodeData, ComponentType, Runtime } from '../types'
import { buildResourceMap } from './normalizer'

// ─── Runtime → Docker image ───────────────────────────────────────────────────

const RUNTIME_IMAGE: Record<Runtime, string> = {
  node:   'node:22-alpine',
  dotnet: 'mcr.microsoft.com/dotnet/aspnet:8.0',
  python: 'python:3.12-alpine',
  go:     'golang:1.22-alpine',
  java:   'eclipse-temurin:21-jre-alpine',
  ruby:   'ruby:3.3-alpine',
  php:    'php:8.3-fpm-alpine',
  rust:   'rust:1.77-alpine',
  nginx:  'nginx:alpine',
  custom: '',  // resolved from custom_image prop
}

// ─── Fallback image per component type (when no runtime prop) ─────────────────

const FALLBACK_IMAGE: Record<ComponentType, string> = {
  server:       'node:22-alpine',
  database:     'postgres:16-alpine',
  loadbalancer: 'nginx:alpine',
  cache:        'redis:7-alpine',
  queue:        'rabbitmq:3-management-alpine',
  storage:      'minio/minio:latest',
  api:          'traefik:v3',
  container:    'node:22-alpine',
  cdn:          'nginx:alpine',
  monitoring:   'prom/prometheus:latest',
}

function resolveImage(
  type: ComponentType,
  props: Record<string, string | number | boolean>
): string {
  if (type === 'server' || type === 'container') {
    const runtime = props.runtime as Runtime | undefined
    if (!runtime) return FALLBACK_IMAGE[type]
    if (runtime === 'custom') return (props.custom_image as string) || FALLBACK_IMAGE[type]
    return RUNTIME_IMAGE[runtime]
  }
  return FALLBACK_IMAGE[type]
}

const DB_ENGINE_IMAGE: Record<string, string> = {
  postgres: 'postgres:16-alpine',
  mysql:    'mysql:8',
  mariadb:  'mariadb:11',
}

const MONITORING_ENGINE_IMAGE: Record<string, string> = {
  prometheus: 'prom/prometheus:latest',
  grafana:    'grafana/grafana:latest',
  datadog:    'datadog/agent:latest',
}

// ─── Port defaults per type ───────────────────────────────────────────────────

const DEFAULT_PORTS: Partial<Record<ComponentType, number>> = {
  server:       3000,
  database:     5432,
  loadbalancer: 80,
  cache:        6379,
  queue:        5672,
  storage:      9000,
  api:          8080,
  container:    8080,
  cdn:          80,
  monitoring:   9090,
}

// ─── Stateful services that need a named volume ───────────────────────────────

const STATEFUL: Set<ComponentType> = new Set(['database', 'cache', 'queue', 'storage', 'monitoring'])

// ─── Generator ───────────────────────────────────────────────────────────────

export function generateDockerCompose(
  nodes: Node<ArchNodeData>[],
  edges: Edge[]
): string {
  if (nodes.length === 0) return '# Add components to the canvas to generate code.'

  // Sort: RE-013 (rede → compute → data → auxiliaries)
  const sorted = [...nodes].sort((a, b) => {
    const order: Record<ComponentType, number> = {
      loadbalancer: 0, cdn: 0, api: 0,
      server: 1, container: 1,
      database: 2, storage: 2,
      cache: 3, queue: 3, monitoring: 3,
    }
    return order[a.data.componentType] - order[b.data.componentType]
  })

  const nameMap = buildResourceMap(sorted)
  const lines: string[] = []
  const volumes: string[] = []

  lines.push(
    '# Generated by Arch Builder — https://archbuilder.io',
    '# Do not edit manually; re-export from the canvas instead.',
    '',
    'services:',
  )

  for (const node of sorted) {
    const svcName = nameMap.get(node.id)!
    const { componentType: type, properties } = node.data

    // ── image ────────────────────────────────────────────────────────────────
    let image = resolveImage(type, properties)
    if (type === 'database' && properties.engine) {
      image = DB_ENGINE_IMAGE[properties.engine as string] ?? image
    }
    if (type === 'monitoring' && properties.engine) {
      image = MONITORING_ENGINE_IMAGE[properties.engine as string] ?? image
    }
    if (type === 'cache' && properties.engine === 'memcached') {
      image = 'memcached:alpine'
    }
    if (type === 'queue' && properties.engine === 'kafka') {
      image = 'confluentinc/cp-kafka:latest'
    }

    // ── depends_on ───────────────────────────────────────────────────────────
    const deps = edges
      .filter(e => e.target === node.id)
      .map(e => nameMap.get(e.source))
      .filter(Boolean)

    // ── port ─────────────────────────────────────────────────────────────────
    const port = (properties.port as number | undefined) ?? DEFAULT_PORTS[type]

    // ── replicas ─────────────────────────────────────────────────────────────
    const replicas = (properties.replicas as number | undefined) ?? 1

    // ── minio command ────────────────────────────────────────────────────────
    const isStorage = type === 'storage'

    lines.push(`  ${svcName}:`)
    lines.push(`    image: ${image}`)
    if (isStorage) lines.push(`    command: server /data --console-address ":9001"`)
    if (replicas > 1) {
      lines.push(`    deploy:`)
      lines.push(`      replicas: ${replicas}`)
    }
    if (port) lines.push(`    ports:\n      - "${port}:${port}"`)

    // environment variables
    const env = buildEnv(type, properties)
    if (env.length > 0) {
      lines.push(`    environment:`)
      env.forEach(e => lines.push(`      ${e}`))
    }

    // volumes
    if (STATEFUL.has(type)) {
      const volName = `${svcName}_data`
      volumes.push(volName)
      lines.push(`    volumes:\n      - ${volName}:/data`)
    }

    if (deps.length > 0) {
      lines.push(`    depends_on:`)
      deps.forEach(d => lines.push(`      - ${d}`))
    }

    lines.push(`    restart: unless-stopped`)
    lines.push('')
  }

  // ── volumes block ─────────────────────────────────────────────────────────
  if (volumes.length > 0) {
    lines.push('volumes:')
    volumes.forEach(v => lines.push(`  ${v}:`))
  }

  return lines.join('\n') // RE-014: LF line endings
}

// ─── Env builder ─────────────────────────────────────────────────────────────

function buildEnv(type: ComponentType, props: Record<string, string | number | boolean>): string[] {
  switch (type) {
    case 'database':
      return [
        'POSTGRES_DB: app',
        'POSTGRES_USER: app',
        'POSTGRES_PASSWORD: "${DB_PASSWORD}"',
      ]
    case 'cache':
      if (props.max_memory) return [`MAXMEMORY: ${props.max_memory}`]
      return []
    case 'storage':
      return [
        'MINIO_ROOT_USER: "${MINIO_ROOT_USER}"',
        'MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"',
      ]
    case 'monitoring':
      return []
    default:
      return []
  }
}
