import type { Node, Edge } from '@xyflow/react'
import type { ArchNodeData, ComponentType } from '../types'
import { buildResourceMap } from './normalizer'

// ─── AWS resource type per component ─────────────────────────────────────────

const AWS_RESOURCE: Record<ComponentType, string> = {
  server:       'aws_instance',
  database:     'aws_db_instance',
  loadbalancer: 'aws_lb',
  cache:        'aws_elasticache_cluster',
  queue:        'aws_sqs_queue',
  storage:      'aws_s3_bucket',
  api:          'aws_api_gateway_rest_api',
  container:    'aws_ecs_service',
  cdn:          'aws_cloudfront_distribution',
  monitoring:   'aws_cloudwatch_dashboard',
}

// ─── Generator ───────────────────────────────────────────────────────────────

export function generateTerraform(
  nodes: Node<ArchNodeData>[],
  edges: Edge[]
): string {
  if (nodes.length === 0) return '# Add components to the canvas to generate code.'

  // RE-013: sort by category
  const sorted = [...nodes].sort((a, b) => {
    const order: Record<ComponentType, number> = {
      loadbalancer: 0, cdn: 0, api: 0,
      server: 1, container: 1,
      database: 2, storage: 2,
      cache: 3, queue: 3, monitoring: 3,
    }
    return order[a.data.componentType] - order[b.data.componentType]
  })

  const nameMap = buildResourceMap(sorted)
  const lines: string[] = []
  const variables = new Map<string, { description: string; sensitive: boolean }>()

  // ── Header (RE-015: comments in English) ──────────────────────────────────
  lines.push(
    '# Generated by Arch Builder — https://archbuilder.io',
    '# Do not edit manually; re-export from the canvas instead.',
    '',
    '# ─── Providers ──────────────────────────────────────────────────────────',
    '',
    'terraform {',
    '  required_providers {',
    '    aws = {',
    '      source  = "hashicorp/aws"',
    '      version = "~> 5.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "aws" {',
    '  region = var.aws_region',
    '}',
    '',
    '# ─── Resources ───────────────────────────────────────────────────────────',
    '',
  )

  // ── Resources ────────────────────────────────────────────────────────────
  for (const node of sorted) {
    const name = nameMap.get(node.id)!
    const { componentType: type, properties } = node.data
    const awsType = AWS_RESOURCE[type]

    lines.push(`# ${node.data.label}`)
    lines.push(`resource "${awsType}" "${name}" {`)

    const body = buildResourceBody(type, name, properties, variables)
    body.forEach(l => lines.push(`  ${l}`))

    lines.push(`  tags = { Name = "${node.data.label}", ManagedBy = "arch-builder" }`)
    lines.push('}')
    lines.push('')
  }

  // ── Security group rules from connections (RE: RF-019) ────────────────────
  if (edges.length > 0) {
    lines.push('# ─── Connections (security group rules) ─────────────────────────────────', '')
    for (const edge of edges) {
      const src = nameMap.get(edge.source)
      const dst = nameMap.get(edge.target)
      if (!src || !dst) continue

      lines.push(`resource "aws_security_group_rule" "${src}_to_${dst}" {`)
      lines.push(`  type              = "ingress"`)
      lines.push(`  from_port         = 0`)
      lines.push(`  to_port           = 65535`)
      lines.push(`  protocol          = "tcp"`)
      lines.push(`  description       = "Allow traffic from ${src} to ${dst}"`)
      lines.push(`  security_group_id = aws_security_group.${dst}.id`)
      lines.push(`  source_security_group_id = aws_security_group.${src}.id`)
      lines.push('}')
      lines.push('')
    }
  }

  // ── Variables (RE-015: comments in English) ───────────────────────────────
  lines.push('# ─── Variables ──────────────────────────────────────────────────────────', '')

  // Always include aws_region
  variables.set('aws_region', { description: 'AWS region to deploy resources', sensitive: false })

  for (const [key, meta] of variables.entries()) {
    lines.push(`variable "${key}" {`)
    lines.push(`  description = "${meta.description}"`)
    if (meta.sensitive) lines.push(`  sensitive   = true`)
    if (key === 'aws_region') lines.push(`  default     = "us-east-1"`)
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

// ─── Resource body builder ───────────────────────────────────────────────────

function buildResourceBody(
  type: ComponentType,
  _name: string,
  props: Record<string, string | number | boolean>,
  variables: Map<string, { description: string; sensitive: boolean }>
): string[] {
  switch (type) {
    case 'server': {
      variables.set('ami_id', { description: 'AMI ID for EC2 instances', sensitive: false })
      variables.set('key_name', { description: 'EC2 key pair name', sensitive: false })
      return [
        `ami           = var.ami_id`,
        `instance_type = "${props.instance_type ?? 't3.medium'}"`,
        `key_name      = var.key_name`,
      ]
    }

    case 'database': {
      const engine = (props.engine as string) ?? 'postgres'
      const engineVersion = engine === 'postgres' ? '16' : engine === 'mysql' ? '8.0' : '11'
      variables.set('db_password', { description: 'Master password for the database', sensitive: true })
      return [
        `engine               = "${engine}"`,
        `engine_version       = "${engineVersion}"`,
        `instance_class       = "db.t3.medium"`,
        `allocated_storage    = ${props.allocated_storage ?? 20}`,
        `db_name              = "app"`,
        `username             = "app"`,
        `password             = var.db_password`,
        `skip_final_snapshot  = true`,
        `publicly_accessible  = false`,
      ]
    }

    case 'loadbalancer': {
      const internal = (props.internal as boolean) ?? false
      return [
        `name               = "${_name}-lb"`,
        `load_balancer_type = "${props.type ?? 'application'}"`,
        `internal           = ${internal}`,
      ]
    }

    case 'cache': {
      const engine = (props.engine as string) ?? 'redis'
      return [
        `cluster_id           = "${_name}"`,
        `engine               = "${engine}"`,
        `node_type            = "cache.t3.micro"`,
        `num_cache_nodes      = 1`,
        `parameter_group_name = "default.${engine}7"`,
      ]
    }

    case 'queue': {
      return [
        `name                      = "${_name}-queue"`,
        `delay_seconds             = 0`,
        `max_message_size          = 262144`,
        `message_retention_seconds = 86400`,
        `receive_wait_time_seconds = 0`,
      ]
    }

    case 'storage': {
      const versioning = (props.versioning as boolean) ?? false
      return [
        `bucket = "${_name}-bucket"`,
        `versioning {`,
        `  enabled = ${versioning}`,
        `}`,
      ]
    }

    case 'api': {
      return [
        `name        = "${_name}"`,
        `description = "API Gateway managed by Arch Builder"`,
      ]
    }

    case 'container': {
      const replicas = (props.replicas as number) ?? 2
      return [
        `name            = "${_name}"`,
        `cluster         = aws_ecs_cluster.main.id`,
        `desired_count   = ${replicas}`,
        `launch_type     = "FARGATE"`,
        `task_definition = aws_ecs_task_definition.${_name}.arn`,
        `network_configuration {`,
        `  subnets          = []`,
        `  assign_public_ip = true`,
        `}`,
      ]
    }

    case 'cdn': {
      return [
        `enabled = true`,
        `default_cache_behavior {`,
        `  allowed_methods        = ["GET", "HEAD"]`,
        `  cached_methods         = ["GET", "HEAD"]`,
        `  target_origin_id       = "${_name}-origin"`,
        `  viewer_protocol_policy = "redirect-to-https"`,
        `  forwarded_values {`,
        `    query_string = false`,
        `    cookies { forward = "none" }`,
        `  }`,
        `}`,
        `restrictions { geo_restriction { restriction_type = "none" } }`,
        `viewer_certificate { cloudfront_default_certificate = true }`,
        `price_class = "${props.price_class ?? 'PriceClass_100'}"`,
      ]
    }

    case 'monitoring': {
      return [
        `dashboard_name = "${_name}-dashboard"`,
        `dashboard_body = jsonencode({`,
        `  widgets = []`,
        `})`,
      ]
    }
  }
}
